version: "3"
services:
  ghost:
    build: .
    environment:
      - server__port=${PORT}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=XPKyYskz
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  mysqldata:
