version: "3"
services:
  ghost:
    image: skyride/ghost:2.38.1
    environment:
      - server__port=${PORT}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${database__connection__database}
      - MYSQL_USER=${database__connection__user}
      - MYSQL_PASSWORD=${database__connection__password}
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  mysqldata:
